<!--

    This file contains the generic code for the website layout
    Altering this file will alter the entire website
    The various functions here are used to construct the layout

    - getRandBanner randomly displays the banner on the pages
    - makeNavBar creates the navigation bar at the top of the website, present on all pages
    - getHeader creates the header title (northampton news)
    - getFooter creates the footer which displays the current year
    - main tag displays the output, generated by calling the other html.php templates
    - if index.html.php is called, it will be buffered and outputted into the main tag

-->

<?php $pagesController = new \Controllers\Home; ?>

<!DOCTYPE html>
<html>

<head>
    <link rel="stylesheet" href="/styles.css"/>
    <meta name="summary" content="Assignment 2024" />
    <title><?=$title?></title>
</head>
<body>

<header>
    <section>
        <h1><?=$pagesController->getHeader();?></h1>
    </section>
</header>

<nav>
    <?=$pagesController->makeNavBar();?>
</nav>

<img src=<?=$pagesController->getRandBanner();?> />

<main>
    <?=$output;?>
</main>

<footer>
    <?=$pagesController->getFooter();?>
</footer>

</body>

</html>